### ISSUE TITLE
Restructuring of MATLAB implementation of Attitude Filter

### ISSUE THREAD

**Issue by srutiv** [pathfinder-for-autonomous-navigation/psim#205]
- Restructuring of `ukf_att_pan_sun_sensors.m`  (@stewartaslan 's  breakout attitude simulation) to have the same inputs and outputs as C++ implementation of the attitude filter. 

- setup initialization of`state` (MATLAB struct that holds info for all calls to the filter in the loop)

**Comment by kylekrol** [comment]
We've decided to move forward with the C++ implementation and testing only as a bug was found in the MATLAB implementation.
