### ISSUE TITLE
sensor_reading

### ISSUE THREAD

**Issue by nhz2** [pathfinder-for-autonomous-navigation/psim#22]
Outputs the sensor readings of one satellite.

**Comment by nhz2** [comment]
To test the control algorithms its important to see if they still work with sensor noise and bias. For attitude control this is mainly gyro bias and noise and magnetometer bias and noise.

Here is some data recorded outside from the two magnetometers. The magnetometers will probably have additional noise and bias from the wheels, magnetorquers, and docking magnets.

The sensor noise models don't have to be super realistic, they just have to be worse than the real worst case noise/bias.

**Comment by nhz2** [comment]
Also the sunsensor model and when the sunsensors can't see the sun.

**Comment by kylekrol** [comment]
In general when there isn't sufficient lighting to detect the sun the ADCS will just return a flag that indicates the sun isn't in view. It only includes a photodiode in the sun vector calculation if the observed voltage is greater than 50% of the maximum expected intensity.

Would this sort of model work in PSim?

**Comment by nhz2** [comment]
Yeah, just modify `sensor_reading.m`

Right now sun sensor calculations are done starting at line 30

I am putting the sun sensor normals in `my_satellite_state.sensors.sunsensor_real_normals` and `my_satellite_state.sensors.sunsensor_measured_normals`: These are size (3,20) matrixes initialized in `initialize_main_state.m`. Should these should have units of volts instead of unitless? Right now they are just the ideal unit vectors. To get the true sun vector, you can call `get_truth('sat2sun body',my_satellite_state.dynamics)`, and implement that functionality in `get_truth.m`, or for now, since `get_truth.m` doesn't exist yet, you can just use the quaternions and `env_sun_vector.m`.

**Comment by kylekrol** [comment]
@nhz2 Do we want to keep this open or close it in favor of making multiple, more specific issues - like #79?

**Comment by tanishqaggarwal** [comment]
Very old
