### ISSUE TITLE
Adjust Attitude Estimator Sun Vector Error Representation

### ISSUE THREAD

**Issue by kylekrol** [pathfinder-for-autonomous-navigation/psim#229]
Currently, we define our expected sun vector distribution as a spherical coordinate representation plus or minus a predetermined uncertainty in `phi` and `theta`. While the sun vector is around the equator this is alright as a given step in `phi` or `theta` traverse a similar distance on the unit sphere. If the expected sun vector, however, is near a pole (plus or minus z), this representation is no longer consistent.

We need to define a local error distribution around the expected sun vector for this to work more consistently.

**Comment by shihaocao** [comment]
![image](https://user-images.githubusercontent.com/14984742/101292612-a1197680-37de-11eb-8bfc-0d4154dd69e4.png)

**Comment by shihaocao** [comment]
![image](https://user-images.githubusercontent.com/14984742/101292740-6b28c200-37df-11eb-9077-70349569c899.png)

**Comment by shihaocao** [comment]
First time scale was on the order of day : hours : mins
