### ISSUE TITLE
Psim Configuration Bug

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/psim#286]
It looks like mutating a psim configuration for a Lin vector breaks things
![image](https://user-images.githubusercontent.com/14984742/103074283-4bdbb400-4597-11eb-9213-104b9f95064e.png)

Not only is it unable to find itself anymore, but it seems like trying to find any field at all will fail after a lin vector has been mutated. Normal parameters though seem unaffected such as ints.

**Comment by shihaocao** [comment]
![image](https://user-images.githubusercontent.com/14984742/103074765-47fc6180-4598-11eb-92a6-3e03fcf490ef.png)

**Comment by shihaocao** [comment]
@kylekrol

**Comment by kylekrol** [comment]
Closed by #285.
