### ISSUE TITLE
Rendezvous Algorithm

### ISSUE THREAD

**Issue by kylekrol** [pathfinder-for-autonomous-navigation/psim#34]
Eventually, everything that has to do with rendezvous.

**Comment by tanishqaggarwal** [comment]
Important: we need to discretize the rendezvous algorithm so that we can run sections of it in every control cycle. Sections should take at most ~20 ms to run.

**Comment by kylekrol** [comment]
@tanishqaggarwal I would hope that the algorithm will run faster than that and we wouldn't need to space it out. That being said, in it's current state it'll be easy to separate out.

**Comment by kylekrol** [comment]
Closing in favor of newer orbit controller issues.
