### ISSUE TITLE
ECI ECEF conversion functions from astropy

### ISSUE THREAD

**Issue by nhz2** [pathfinder-for-autonomous-navigation/psim#87]

**Comment by kylekrol** [comment]
Just curious what's going on here/where they may be used.

**Comment by nhz2** [comment]
We were having trouble getting our orbit propagator to match up with the grace data under about 100m after one orbit. My sketchy eci to ecef conversion was suspect. The astropy eci to ecef conversion automatically downloads the earth orientation parameters from the internet, so its probably the most accurate/easiest way to do the conversion.

**Comment by kylekrol** [comment]
Gotcha - sounds good!

**Comment by nhz2** [comment]
#105
